# Train Forecasting Model

## Imports

In [1]:
import os
import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import mean_squared_error, mean_absolute_error

import xgboost as xgb

import matplotlib.pyplot as plt
import seaborn as sns

import joblib

## Loading Data

In [2]:
PROCESSED_DATA_DIR= '../data/processed'
MODELS_DIR= '../models'

In [3]:
data_path= os.path.join(PROCESSED_DATA_DIR, 'forecasting_training_data.csv')

In [4]:
df= pd.read_csv(filepath_or_buffer= data_path)

In [5]:
df.head()

    sale_date         category  units_sold  daily_revenue
0  2016-09-15    health_beauty           3         134.97
1  2016-10-03    fashion_shoes           1          29.99
2  2016-10-03  furniture_decor           2         194.80
3  2016-10-03   sports_leisure           2          58.39
4  2016-10-03             toys           1         128.90

In [6]:
df.describe()

         units_sold  daily_revenue
count  18311.000000   18311.000000
mean       5.932936     712.442297
std        7.285815     969.197817
min        1.000000       3.850000
25%        1.000000     119.730000
50%        3.000000     349.900000
75%        8.000000     923.335000
max      192.000000   17667.020000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18311 entries, 0 to 18310
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sale_date      18311 non-null  object
 1   category       18311 non-null  object
 2   units_sold     18311 non-null  int64
 3   daily_revenue  18311 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 572.3+ KB

In [8]:
df.shape

(18311, 4)